Controllers/KwisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MvcMovie.Controllers
{
    public class KwisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KrisnaldoApp.Controllers
{
    public class LinksController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/Voorbeeldmail.cshtml
@model KrisnaldoApp.Models.Sponsor

@{
    ViewData["Title"] = "Voorbeeldmail";
}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>

<div ng-app="" >

    <div class="col-md-12">
        <div class="alert alert-warning">
            <p>Vul hier eerst de variabele gegevens in</p>
            <hr/>
            <p>Voorstel voor prijs van deze sponsor: <input type="text" ng-model="prijsvoorstel"></p>
            <p>Bedrijfsnaam: <input type="text" ng-model="bedrijfsnaam"></p>
            <p>Afzendernaam: <input type="text" ng-model="afzendernaam"></p>
            <p>GSM nummer (zonder +32 en zonder nul, vb. 477069583):<input type="text" ng-model="gsmnummer"></p>
            <p>Eventuele extra aanspreking:<input type="text" ng-model="extraaanspreking"></p>
            
        </div>
        <div class="alert alert-success">
            Hieronder kan je het resultaat zien dat je dan kan copy-pasten in een mail of in het contactformuliertje van hun website.
            <b>Vergeet aub niet de Exel aan te vullen via <a  target="_blank" href="https://docs.google.com/spreadsheets/d/1Lbg03h5B07Vz0VcM5JXVJ7w1HU8-4goRCQlhNm3rvjU/edit#gid=505297403">deze link.</a>.
            </b>
        </div>
    </div>
    <hr />
    <div id="myInput">
    <p>Geachte <span ng-bind="extraaanspreking"></span>,</p>
    <p>Op zaterdagavond 21 april 2018 in zaal Geitenhove te Hooglede organiseren we een algemene quiz met onze voetbalploeg ("De Krisnaldos"), die uitkomt in het Roeselaars Liefhebbersvoetbal. Hierbij zijn we nog op zoek naar sponsors die ons zouden willen steunen, dit kan met behulp van prijzenmateriaal voor de deelnemende teams: <span ng-bind="prijsvoorstel"></span> zou bijvoorbeeld ideaal zijn.</p>
    <p>We verwachten voor deze quiz een aanwezigheid van 150 &agrave; 200 personen, verdeeld over 38 teams. De prijzen kunnen vari&euml;ren van kleine gadgets tot iets meer waardevolle prijzen voor de winnaars. In ruil daarvoor zal het logo van <span ng-bind="bedrijfsnaam"></span> te zien zijn op <b>de antwoordformulieren, de drankkaarten en de presentatie zelf</b>. Als sponsor van de quiz krijgt u ook <b>extra zichtbaarheid op onze website: <a href="http://krisnaldos.be/sponsors">http://krisnaldos.be/sponsors</a></b></p>
    <p>
        Hieronder vindt u de link naar het Facebook evenement en de foto&acute;s van de voorbij drie edities:
        <ul>
            <li>Het Facebook-event: <a href="https://www.facebook.com/events/949548311859773/">https://www.facebook.com/events/949548311859773/</a></li>
            <li>Kwisnaldo's 2015: <a href="http://krisnaldos.be/Albums/kwisnaldos2015">http://krisnaldos.be/Albums/kwisnaldos2015</a></li>

            <li>Kwisnaldo's 2016: <a href="http://krisnaldos.be/Albums/kwisnaldos2016">http://krisnaldos.be/Albums/kwisnaldos2016</a></li>

            <li>Kwisnaldo's 2017: <a href="http://krisnaldos.be/Albums/kwisnaldos2017">http://krisnaldos.be/Albums/kwisnaldos2017</a></li>
        </ul>
    </p>
    <p>Zou <span ng-bind="bedrijfsnaam"></span> hier eventueel in ge&iuml;nteresseerd zijn? U zou ons er alvast een groot plezier mee doen. Alvast bedankt voor uw antwoord!</p>
    <p>
        Met vriendelijke groeten,<br />
        <span ng-bind="afzendernaam"></span>
        <br/>
        <i>Bereikbaar op dit e-mailadres of via het GSM-nummer +32 <span ng-bind="gsmnummer"></span></i>
    </p>
        </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - De Krisnaldo's</title>
    <meta name="description" content="Een website over het reilen en zeilen van de Krisnaldo's." />
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/errorpage.css" />
        <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="~/css/dataTables.bootstrap.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/font-awesome.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/dataTablesCustomizing.js" asp-append-version="true"></script>
        <script src="~/js/jquery.dataTables.min.js" asp-append-version="true"></script>
        <script src="~/js/dataTables.bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/d3/d3.min.js"></script>
        <script src="~/lib/mosaicflow/jquery.mosaicflow.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/additional-methods.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.3.0/d3.min.js"
                asp-fallback-src="~/lib/d3/d3.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/mosaicflow/jquery.mosaicflow.min.js"></script>
    </environment>
    @RenderSection("scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">De Krisnaldo's</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Kwis" asp-action="Index">Kwisnaldo's</a></li>
                    <li><a asp-area="" asp-controller="Albums" asp-action="Index">Albums</a></li>
                    <li><a asp-area="" asp-controller="Sponsors" asp-action="Index">Sponsors</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Statistieken
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Spelers" asp-action="Index">Spelers</a></li>
                            <li><a asp-area="" asp-controller="Matchen" asp-action="Index">Matchen</a></li>
                            <li><a asp-area="" asp-controller="Seizoenen" asp-action="Index">Seizoenen</a></li>
                        </ul>
                    </li>
                    <!--<li><a asp-area="" asp-controller="Contact" asp-action="Index">Contact</a></li>-->
                    <li><a asp-area="" asp-controller="Links" asp-action="Index">Links</a></li>
                    
                    
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
        <div class="container body-content margin-top">
            <br />
            @RenderBody()
            <!--<hr />
        <footer>
                <p>&copy; 2016 - Krisnaldo-website</p>
        </footer>-->
        </div>
</body>
</html>