Controllers/ExtraController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Text;
using System.Xml;
using KrisnaldoApp.XMLMatch;
using System.Threading.Tasks;
using KrisnaldoApp.Models;
using Microsoft.AspNetCore.Builder;
using KrisnaldoApp.Data;
using Microsoft.AspNetCore.Authorization;

namespace MvcMovie.Controllers
{
    public class ExtraController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ApplicationDbContext _context;

        public ExtraController(ApplicationDbContext context,IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }
        public IActionResult AzureAccount()
        {
            return View();
        }

        public IActionResult DeployOnSmarterASP()
        {
            return View();
        }

        public IActionResult TestEensException()
        {
            throw new Exception();
        }

        public IActionResult NotFoundRonaldo()
        {
            Response.StatusCode = 404;
            return View();
        }


        public IActionResult RelationeleDatabase()
        {
            return View();
        }
        public IActionResult AngularJSDemo()
        {
            return View();
        }

        [Authorize]
        public IActionResult Refresh()
        {
           
            try
            {
                ViewBag.Status = "Het is gelukt om een refresh te doen van de data. Eerst werden alle data-tabellen leeggemaakt,"+User.Identity.Name+" en er zijn in totaal "+ SeedData.InitializeBis(_context, _hostingEnvironment)+ " rijen opnieuw toegevoegd aan de verschillende tabellen in de database.";
            }
            catch
            {
                ViewBag.Status = "Het is niet gelukt.";
            }
            return View();
        }


        public async Task<IActionResult> MailGenerator()
        {
            return View("Voorbeeldmail");
        }
    }
}

Views/Extra/AngularJSDemo.cshtml
@{
    ViewData["Title"] = "AngularJSDemo";
}
<div ng-controller="Demo">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">AngularJS Demo</h3>
        </div>
        <div class="panel-body">
            <div ng-repeat="item in data | filter:search.text"
                 ng-bind-html="item.text | highlight:search.text">
                Cristiano Ronaldo dos Santos Aveiro (Funchal, 5 februari 1985) is een Portugees profvoetballer die bij voorkeur als linksbuiten speelt. Hij verruilde in 2009 Manchester United voor Real Madrid, dat 94 miljoen euro voor hem betaalde. Daarmee was hij tot 2013 de duurste voetballer aller tijden. In 2015 werd hij de all-time topscorer van de UEFA Champions League/Europacup I alsmede de meest scorende Real Madrid-speler ooit. Ronaldo debuteerde in 2003 in het Portugees voetbalelftal, waarvan hij in 2008 aanvoerder, in 2014 topscorer aller tijden en in 2016 recordinternational werd. Hij won in 2016 het EK met zijn land. Ronaldo werd in 2008, 2013, 2014, 2016 en 2017 uitgeroepen tot beste voetballer ter wereld.
            </div>
            <hr />
            Met het invullen van de box kan je tekst uit het bovenvermelde tekstje filteren met behulp van Angular JS.
            <input type="text" placeholder="Filter" ng-model="search.text">
        </div>
    </div>
</div>

<style>
    .highlighted {
        background: yellow;
    }
</style>

Views/Extra/AzureAccount.cshtml
@{
    ViewData["Title"] = "Uitleg over Azure-account";
}
<h2>Mijn Azure-account</h2>
<p>Ik heb al geëxperimenteerd met Microsoft Azure. Dit is een screenshot van de resources die ik gebruikt heb. Nu kan ik dit niet meer gebruiken omdat mijn gratis proefabonnement verlopen is. Voor een hobbyist zijn de services van Microsoft Azure vrij duur. Ik heb nu een betalende account op SmarterASP waar ik ook via Visual Studio mijn webapplicatie kan deployen.</p>
<img src="~/images/azure/almijnresources.PNG" class="img-thumbnail center-block" alt="Alle Resources">
<p>Ook hostte ik een webservice via deze account, die ik succesvol aanriep vanuit deze applicatie. De code van mijn webservice kan je nog steeds downloaden via <a target="_blank" href="http://github.com/judochampion">mijn GitHub-pagina</a>. Ter illustratie vind je hieronder de WSDL.</p>
<img src="~/images/azure/wsdl.PNG" class="img-thumbnail center-block" alt="Mijn WSDL">

Views/Extra/DeployOnSmarterASP.cshtml
@{
    ViewData["Title"] = "How To Deploy on SmarterASP";
}

<p>Zoals vermeld op de pagina over <a asp-area="" asp-controller="Extra" asp-action="AzureAccount">mijn Azure Account</a>, heb ik nu een betalende account op SmarterASP waar ik ook via Visual Studio mijn webapplicatie kan deployen. Dit ging echter niet van een leien dakje, hieronder is er uitleg die ik zelf heb opgesteld en die ik dan zou willen geven aan de mensen van SmarterASP om hen te tonen hoe ze mensen met gelijkaardige problemen kunnen helpen.</p>
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">How To Deploy on SmarterASP</h3>
    </div>
    <div class="panel-body">
        <p>In what follows I would like to share things I have learnt while trying to deploy an ASP.NET Core Application via Visual Studio on SmarterASP.</p>
        <p>The recommended steps are:</p>
        <ul>
            <li>
                Create the database of this type: MSSQL 2014.
                <ul>
                    <li>You can choose a password.</li>
                    <li>Then you are able to find the connection string. Remark that the password will not be filled in there, you need to add it there instead of ‘YOUR_DB_PASSWORD’.</li>
                    <li>Why MSSQL and not MySQL? Well, as we are working with one product of Microsoft on the one hand, it makes sense to use also the Microsoft way of storing data. But I read on StackOverflow that developers easily managed to implement ASP.NET projects with MySQL-databases as well.</li>
                </ul>
            </li>
            <li>Fill in the connection string in the application.json-file. Where you do it exactly does not really matter, as long as you make sure that in this specific configuration method of the StartUp.cs-file, the correct connection string is added to the deployed application.</li>
            <li>
                Before actually deploying, there is another set of precautions:
                <ul>
                    <li>For deploying via VS to SmarterASP, you need to be on the Advanced Plan. The Basic Plan does not provide you with that feature. I think you can also deploy ASP.Net Core Applications without using VS on the Basic Plan, but do not have experience with it. Do not forget to enable the VS Deployment in your control panel. After enabling, you can just copy all settings that you need to fill in in Visual Studio from that information box. (More details can be found in the Knowledge Base of Smarter ASP)</li>
                    <li>
                        During deployment, they also ask you to enable an initial migration while deploying. A simple advice: Don’t do it. If you do, you will certainly have the error of Visual Studio not being authorized to access the database. This took me a lot of time to find out that I really need to uncheck this box when I want to deploy to Visual Studio and also a coworker of the chat service of SmarterASP was very helpful to overcome this issue. <ul>
                            <li>
                                How do I do the migration than? How do I create the initial tables? Well, there are still enough other options:
                                <ul>
                                    <li>You can take the .mdf-file of your local database and import it in your database that was created in step 1. In this way, your database is populated with exactly the same data as in your local database. </li>
                                    <li>You can open up Microsoft SQL Server Management Studio (which is freeware) and manually create your database or dump a few queries there to create the tables you want.</li>
                                    <li>OR You can let the application take care of all that on the start-up of the application on the server, by using the command context.Database.Migrate(). This simply works :) !</li>
                                </ul>
                            </li>

                        </ul>
                    </li>
                </ul>
            </li>
            <li>As a last remark, you know there is also the possibility to perform context.Database.EnsureDeleted() and its counterpart EnsureCreated(). Don’t do it. It is not gonna work and also on deploying applications in production it is in general a bit rookie to do it. Migrations are the way to go, the other methods mentioned above are only a good practice in development environments (so when you are experimenting on your localhost). </li>
        </ul><p>I hope this can help you out for overcoming deploying issues and that I saved you some valuable time of your life. I would like to refer to my github account to find full projects with reference code: www.github.com/judochampion.</p>
        <p>Also for some reason, I had the problem that the connection string was not loaded correctly from the appsettings.json file, I hardcoded this to quickly solve the issue.</p>
        <img src="~/images/smarterasp/hardcodefix.png" class="img-thumbnail center-block" alt="HardCode Fix">
    </div>
</div>
<p>

Views/Extra/NotFoundRonaldo.cshtml
@{
    ViewData["Title"] = "Not Found";
}
<h2>Foute link</h2>
<p>De link die je hebt gevormd leidt nergens naar, zelfs Ronaldo weet niet wat ermee te doen. Mogelijks heb je een verkeerde albumnaam, of een matchdatum die niet bestaat... Ga terug naar de <a asp-area="" asp-controller="Sponsor" asp-action="Index">de home-pagina</a>
    <img src="~/images/extra/notfoundronaldo.jpg" class="img-rounded img-responsive" alt="RonaldoNotFound">

Views/Extra/Refresh.cshtml
@{
    ViewData["Title"] = "Refresh";
}
<h2>Refresh</h2>
<p>@ViewBag.Status </p>

Views/Extra/RelationeleDatabase.cshtml
@{
    ViewData["Title"] = "Relationele Database";
}
<h2>Relationele Database</h2>
<p>De data komt uit een database, waarvan ik de relaties op onderstaande manier heb opgezet. Deze database wordt <i>geseed</i> met XML-bestanden telkens wanneer de applicatie opnieuw opstart op de server.</p>
<img src="~/images/dbdiagrams/RelationalDBOfData.png" class="img-thumbnail center-block" alt="SchemaRelationeleDatabase" width="304">